// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcg_o-CuYcm_dnBpH630wfgfyubMz_Eyk',
    appId: '1:357254345215:web:f663bd246d551918e377ca',
    messagingSenderId: '357254345215',
    projectId: 'hendriksonpetzold-firebase',
    authDomain: 'hendriksonpetzold-firebase.firebaseapp.com',
    storageBucket: 'hendriksonpetzold-firebase.appspot.com',
    measurementId: 'G-GZSXVMSG59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT6KYuEBGPsJQ5Ca2b-PPi2Bs_BBHr-i8',
    appId: '1:357254345215:android:3cfef0f3636e32e3e377ca',
    messagingSenderId: '357254345215',
    projectId: 'hendriksonpetzold-firebase',
    storageBucket: 'hendriksonpetzold-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuTb33wpZR2RXS5Lt5h_zlgcmzTpb6SVA',
    appId: '1:357254345215:ios:b1ae5141f0dd8bd0e377ca',
    messagingSenderId: '357254345215',
    projectId: 'hendriksonpetzold-firebase',
    storageBucket: 'hendriksonpetzold-firebase.appspot.com',
    iosClientId: '357254345215-13i8erf56dfiivnrk2pukntfdqcfnbi8.apps.googleusercontent.com',
    iosBundleId: 'com.hendriksonpetzold.app',
  );
}
